-file("/home/mariano/bin/erl-22.2/lib/parsetools-2.1.8/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(dtu_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 101).

make_token(Name, Line, Chars) when is_list(Chars) ->
    {token, {Name, Line, list_to_atom(Chars)}};
make_token(Name, Line, Chars) ->
    {token, {Name, Line, Chars}}.

make_token(Name, Line, Chars, Fun) ->
    {token, {Name, Line, Fun(Chars)}}.

make_str_token(Name, Line, Chars) ->
    {token, {Name, Line, list_to_binary(Chars)}}.

%endls(Chars) ->
%    lists:filter(fun (C) -> C == $\n orelse C == $; end, Chars).

build_string(Type, Chars, Line, Len) ->
  String = get_string_content(Chars, Line, Len),
  {token, {Type, Line, list_to_binary(String)}}.

get_string_content(Chars, Line, Len) ->
    unescape_string(lists:sublist(Chars, 2, Len - 2), Line).

unescape_string(String, Line) -> unescape_string(String, Line, []).

unescape_string([], _Line, Output) ->
  lists:reverse(Output);
unescape_string([$\\, Escaped | Rest], Line, Output) ->
  Char = map_escaped_char(Escaped, Line),
  unescape_string(Rest, Line, [Char|Output]);
unescape_string([Char|Rest], Line, Output) ->
  unescape_string(Rest, Line, [Char|Output]).

map_escaped_char(Escaped, Line) ->
  case Escaped of
    $\\ -> $\\;
    $/ -> $/;
    $\" -> $\";
    $\' -> $\';
    $\( -> $(;
    $b -> $\b;
    $d -> $\d;
    $e -> $\e;
    $f -> $\f;
    $n -> $\n;
    $r -> $\r;
    $s -> $\s;
    $t -> $\t;
    $v -> $\v;
    _ -> throw({error, {Line, fn_lexer, ["unrecognized escape sequence: ", [$\\, Escaped]]}})
  end.

-file("/home/mariano/bin/erl-22.2/lib/parsetools-2.1.8/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/home/mariano/src/erl/dtu/src/dtu_lexer.erl", 357).
yystate() -> 76.

yystate(79, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(78, [32|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [13|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, [10|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line+1, Tlen+1, 35, Tlen);
yystate(78, [9|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 35, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,78};
yystate(77, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(76, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line+1, Tlen+1, Action, Alen);
yystate(76, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 63 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [124|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [94|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [42|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [43|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [37|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [38|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [33|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 63 ->
    yystate(64, Ics, Line, Tlen+1, 32, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,75};
yystate(74, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(73, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(72, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line+1, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line+1, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [124|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [94|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [42|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [43|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [37|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [38|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [33|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 63 ->
    yystate(64, Ics, Line, Tlen+1, 12, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,68};
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,67};
yystate(66, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line+1, Tlen+1, Action, Alen);
yystate(66, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line+1, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [124|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [94|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [42|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [43|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [37|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [38|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [33|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 63 ->
    yystate(64, Ics, Line, Tlen+1, 31, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,64};
yystate(63, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [32|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [13|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [10|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line+1, Tlen+1, 34, Tlen);
yystate(62, [9|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,62};
yystate(61, [92|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 14, Tlen);
yystate(61, [39|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 14, Tlen);
yystate(61, [10|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line+1, Tlen+1, 14, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(53, Ics, Line, Tlen+1, 14, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(53, Ics, Line, Tlen+1, 14, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(53, Ics, Line, Tlen+1, 14, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(53, Ics, Line, Tlen+1, 14, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,61};
yystate(60, [72|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 6, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,60};
yystate(59, [101|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [69|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,59};
yystate(58, [124|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [94|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [47|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [46|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [45|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [42|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [43|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [37|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [38|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [33|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 63 ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,58};
yystate(57, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(56, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line+1, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line+1, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [46|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 1, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,51};
yystate(50, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(49, [124|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [94|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [47|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [46|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [45|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [42|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [43|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [37|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [38|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [34|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [33|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 63 ->
    yystate(58, Ics, Line, Tlen+1, 30, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,49};
yystate(48, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(46, [92|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 13, Tlen);
yystate(46, [34|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 13, Tlen);
yystate(46, [10|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(54, Ics, Line, Tlen+1, 13, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,46};
yystate(45, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line+1, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [92|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [34|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [10|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,43};
yystate(42, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line+1, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line+1, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(39, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line+1, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line+1, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [92|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 28, Tlen);
yystate(37, [34|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 28, Tlen);
yystate(37, [10|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line+1, Tlen+1, 28, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, 28, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(29, Ics, Line, Tlen+1, 28, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(29, Ics, Line, Tlen+1, 28, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(29, Ics, Line, Tlen+1, 28, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,37};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [47|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [45|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [46|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 17, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,36};
yystate(35, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line+1, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line+1, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line+1, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(29, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line+1, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [45|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,28};
yystate(27, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(26, [92|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 29, Tlen);
yystate(26, [34|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 29, Tlen);
yystate(26, [10|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line+1, Tlen+1, 29, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, 29, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(34, Ics, Line, Tlen+1, 29, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, 29, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(34, Ics, Line, Tlen+1, 29, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,26};
yystate(25, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line+1, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 20, Tlen);
yystate(23, [45|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 20, Tlen);
yystate(23, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 20, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(23, Ics, Line, Tlen+1, 20, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(23, Ics, Line, Tlen+1, 20, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(23, Ics, Line, Tlen+1, 20, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,23};
yystate(22, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line+1, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, [45|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, [46|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(21, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 21, Tlen);
yystate(19, [45|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 21, Tlen);
yystate(19, [46|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 21, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(19, Ics, Line, Tlen+1, 21, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(19, Ics, Line, Tlen+1, 21, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(19, Ics, Line, Tlen+1, 21, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,19};
yystate(18, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line+1, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(17, [45|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,17};
yystate(16, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line+1, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 10, Tlen);
yystate(15, [58|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 10, Tlen);
yystate(15, [34|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 10, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(23, Ics, Line, Tlen+1, 10, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(19, Ics, Line, Tlen+1, 10, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,15};
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 24, Tlen);
yystate(14, [45|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 24, Tlen);
yystate(14, [46|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 24, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Tlen+1, 24, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(14, Ics, Line, Tlen+1, 24, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(14, Ics, Line, Tlen+1, 24, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,14};
yystate(13, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line+1, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [96|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 15, Tlen);
yystate(12, [92|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(12, [10|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line+1, Tlen+1, 15, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(24, Ics, Line, Tlen+1, 15, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 91 ->
    yystate(24, Ics, Line, Tlen+1, 15, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(24, Ics, Line, Tlen+1, 15, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(24, Ics, Line, Tlen+1, 15, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,12};
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(11, [45|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(11, [46|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,11};
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(10, [45|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(10, [46|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,10};
yystate(9, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line+1, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line+1, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [92|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 27, Tlen);
yystate(5, [34|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 27, Tlen);
yystate(5, [10|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line+1, Tlen+1, 27, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, [47|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, [45|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, [46|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(3, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 63, C =< 90 ->
    yystate(3, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(3, Ics, Line, Tlen+1, 16, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,3};
yystate(2, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line+1, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(0, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLen, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLen, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLen, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLen, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLen, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLen, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLen, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, _, _, _) ->
    yyaction_33();
yyaction(34, _, _, _) ->
    yyaction_34();
yyaction(35, _, _, _) ->
    yyaction_35();
yyaction(36, _, _, _) ->
    yyaction_36();
yyaction(37, _, _, _) ->
    yyaction_37();
yyaction(38, _, _, _) ->
    yyaction_38();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 42).
yyaction_0(TokenChars, TokenLine) ->
     make_token (float, TokenLine, TokenChars, fun erlang : list_to_float / 1) .

-compile({inline,yyaction_1/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 43).
yyaction_1(TokenChars, TokenLine) ->
     make_token (integer, TokenLine, TokenChars, fun erlang : list_to_integer / 1) .

-compile({inline,yyaction_2/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 46).
yyaction_2(TokenChars, TokenLine) ->
     make_token (open, TokenLine, TokenChars) .

-compile({inline,yyaction_3/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 47).
yyaction_3(TokenChars, TokenLine) ->
     make_token (close, TokenLine, TokenChars) .

-compile({inline,yyaction_4/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 48).
yyaction_4(TokenChars, TokenLine) ->
     make_token (open_list, TokenLine, TokenChars) .

-compile({inline,yyaction_5/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 49).
yyaction_5(TokenChars, TokenLine) ->
     make_token (close_list, TokenLine, TokenChars) .

-compile({inline,yyaction_6/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 50).
yyaction_6(TokenChars, TokenLine) ->
     make_token (open_map, TokenLine, TokenChars) .

-compile({inline,yyaction_7/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 51).
yyaction_7(TokenChars, TokenLine) ->
     make_token (close_map, TokenLine, TokenChars) .

-compile({inline,yyaction_8/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 53).
yyaction_8(TokenChars, TokenLine) ->
     make_token (sep, TokenLine, TokenChars) .

-compile({inline,yyaction_9/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 54).
yyaction_9(TokenChars, TokenLine) ->
     make_token (hash, TokenLine, TokenChars) .

-compile({inline,yyaction_10/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 55).
yyaction_10(TokenChars, TokenLine) ->
     make_token (colon, TokenLine, TokenChars) .

-compile({inline,yyaction_11/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 56).
yyaction_11(TokenChars, TokenLine) ->
     make_token (anno, TokenLine, TokenChars) .

-compile({inline,yyaction_12/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 57).
yyaction_12(TokenChars, TokenLine) ->
     make_token (alt, TokenLine, TokenChars) .

-compile({inline,yyaction_13/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 60).
yyaction_13(TokenChars, TokenLen, TokenLine) ->
     build_string (dstr, TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_14/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 61).
yyaction_14(TokenChars, TokenLen, TokenLine) ->
     build_string (sstr, TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_15/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 62).
yyaction_15(TokenChars, TokenLen, TokenLine) ->
     build_string (bstr, TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_16/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 65).
yyaction_16(TokenChars, TokenLine) ->
     make_token (upid, TokenLine, TokenChars) .

-compile({inline,yyaction_17/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 66).
yyaction_17(TokenChars, TokenLine) ->
     make_token (loid, TokenLine, TokenChars) .

-compile({inline,yyaction_18/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 67).
yyaction_18(TokenChars, TokenLine) ->
     make_token (qloid, TokenLine, TokenChars) .

-compile({inline,yyaction_19/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 68).
yyaction_19(TokenChars, TokenLine) ->
     make_token (qupid, TokenLine, TokenChars) .

-compile({inline,yyaction_20/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 69).
yyaction_20(TokenChars, TokenLine) ->
     make_token (upkw, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_21/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 70).
yyaction_21(TokenChars, TokenLine) ->
     make_token (lokw, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_22/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 71).
yyaction_22(TokenChars, TokenLine) ->
     make_token (upvar, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_23/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 72).
yyaction_23(TokenChars, TokenLine) ->
     make_token (lovar, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_24/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 74).
yyaction_24(TokenChars, TokenLine) ->
     make_token (uptag, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_25/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 75).
yyaction_25(TokenChars, TokenLine) ->
     make_token (lotag, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_26/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 77).
yyaction_26(TokenChars, TokenLen, TokenLine) ->
     make_str_token (rkw, TokenLine, get_string_content (tl (TokenChars), TokenLine, TokenLen - 1)) .

-compile({inline,yyaction_27/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 78).
yyaction_27(TokenChars, TokenLen, TokenLine) ->
     make_str_token (rvar, TokenLine, get_string_content (tl (TokenChars), TokenLine, TokenLen - 1)) .

-compile({inline,yyaction_28/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 79).
yyaction_28(TokenChars, TokenLen, TokenLine) ->
     make_str_token (rid, TokenLine, get_string_content (tl (TokenChars), TokenLine, TokenLen - 1)) .

-compile({inline,yyaction_29/3}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 80).
yyaction_29(TokenChars, TokenLen, TokenLine) ->
     make_str_token (rtag, TokenLine, get_string_content (tl (TokenChars), TokenLine, TokenLen - 1)) .

-compile({inline,yyaction_30/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 82).
yyaction_30(TokenChars, TokenLine) ->
     make_token (symbol, TokenLine, TokenChars) .

-compile({inline,yyaction_31/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 83).
yyaction_31(TokenChars, TokenLine) ->
     make_token (symbol, TokenLine, TokenChars) .

-compile({inline,yyaction_32/2}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 86).
yyaction_32(TokenChars, TokenLine) ->
     make_token (dot, TokenLine, TokenChars) .

-compile({inline,yyaction_33/0}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 90).
yyaction_33() ->
     skip_token .

-compile({inline,yyaction_34/0}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 91).
yyaction_34() ->
     skip_token .

-compile({inline,yyaction_35/0}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 92).
yyaction_35() ->
     skip_token .

-compile({inline,yyaction_36/0}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 95).
yyaction_36() ->
     skip_token .

-compile({inline,yyaction_37/0}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 96).
yyaction_37() ->
     skip_token .

-compile({inline,yyaction_38/0}).
-file("/home/mariano/src/erl/dtu/src/dtu_lexer.xrl", 97).
yyaction_38() ->
     skip_token .

-file("/home/mariano/bin/erl-22.2/lib/parsetools-2.1.8/include/leexinc.hrl", 313).
